//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MetamodelAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetamodelEntities : DbContext
    {
        public MetamodelEntities()
            : base("name=MetamodelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAttribute> tblAttribute { get; set; }
        public virtual DbSet<tblFactType> tblFactType { get; set; }
        public virtual DbSet<tblModel> tblModel { get; set; }
        public virtual DbSet<tblObjectType> tblObjectType { get; set; }
        public virtual DbSet<tblPredicator> tblPredicator { get; set; }
    }
}
